name: Static Build

on:
  push:
    branches:
      - main

jobs:
   builds:
      if: github.repository == 'cris21512/PageMaster'
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
         - name: Chekout repo
           uses: actions/chekout@v4

         - name: Setup Python
           uses: actions/setup-python@v5
           with:
              python-version: "3.13.1"

         - name: Run build script
           run: |
             chmod +x ./link_master/remote_build.sh
             ./link_master/remote_build.sh

         - name: Commit and Push changes
           uses: stefanzweifel/git-auto-commit-action@v5
           with:
              commit_message: Update static build
              commit_user_name: cris21512 [GitHub Actions]
              commit_user_email: mastercrack2112.5@gmail.com
              commit_author: Master <mastercrack2112.5@gmail.com>
